Controllers/ContatosController.cs
using Microsoft.AspNetCore.Mvc;
using RecentMemory.Contexts;

namespace RecentMemory.Controllers
{
    [Route("[Controller]")]
    public class ContatosController : Controller
    {
        RecentMemoryContext context = new RecentMemoryContext();
        public IActionResult index()
        {
            var listaContatos = context.Contatos.ToList();

            ViewBag.listaContatos = listaContatos;

            return View();
        }

    }
}

Controllers/LembretesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RecentMemory.Contexts;
using RecentMemory.Models;

namespace RecentMemory.Controllers
{
    [Route("[Controller]")]
    public class LembretesController : Controller
    {
        RecentMemoryContext context = new RecentMemoryContext();

        public IActionResult Index()
        {
            // Lista de lugares 
            var listaLugares = context.Lugares.ToList();
            ViewBag.ListaLugares = listaLugares;

            // Lista de contatos
            var listaContatos = context.Contatos.ToList();
            ViewBag.ListaContatos = listaContatos;

            var listaLembretes = context.Lembretes.Include(x => x.LugaresLembretes).ThenInclude(x => x.Lugares).Include(x => x.ContatoLembretes).ThenInclude(x => x.Contatos).OrderBy(x => x.Prioridade).ToList();

            ViewBag.listaLembretes = listaLembretes;

            return View();
        }

        [HttpPost]
        public IActionResult AdicionarLembrete(Lembrete Lembrete, string[] contatos, string[] lugares)
        {
            // Procurando os dados do usuario
            var usuario = context.Usuarios.FirstOrDefault(x => x.Email == HttpContext.Session.GetString("Usuario"));

            Lembrete.UsuarioId = usuario.Id;

            // Inserindo Lembrete
            context.Add(Lembrete);

            context.SaveChanges();

            // Vinculo com contatos
            if (contatos != null)
            {
                foreach (var ct in contatos)
                {
                    context.ContatosLembretes.Add(new ContatoLembrete
                    {
                        LembretesId = Lembrete.Id,
                        ContatosId = int.Parse(ct)
                    });
                }
            }

            // Vinculo com lugares
            if (lugares != null)
            {
                foreach (var lg in lugares)
                {
                    context.LugaresLembretes.Add(new LugaresLembrete
                    {
                        LembretesId = Lembrete.Id,
                        LugaresId = int.Parse(lg)
                    });
                }
            }

            // Salva tudo de uma vez
            context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpDelete("Remover/{id}")]
        public IActionResult Remover(int id)
        {
            // Procurando lugares que contenham
            var listaLugaresLembretes = context.LugaresLembretes.Where(x => x.LembretesId == id).ToList();

            if (listaLugaresLembretes != null && listaLugaresLembretes.Count > 0)
            {
                foreach (var lg in listaLugaresLembretes)
                {
                    context.Remove(lg);
                }

                context.SaveChanges();
            }

            // Procurando contatos que contenham
            var listaContatosLembretes = context.ContatosLembretes.Where(x => x.LembretesId == id).ToList();

            if (listaContatosLembretes != null && listaContatosLembretes.Count > 0)
            {
                foreach (var ct in listaContatosLembretes)
                {
                    context.Remove(ct);
                }

                context.SaveChanges();
            }

            Lembrete lembrete = context.Lembretes.FirstOrDefault(l => l.Id == id);

            context.Remove(lembrete);

            context.SaveChanges();

            return RedirectToAction("Index");
        }
        
          
            [HttpPut("Editar")]
            public IActionResult Editar([FromBody] Lembrete lembreteAtualizado)
            {
                var lembreteDb = context.Lembretes.FirstOrDefault(l => l.Id == lembreteAtualizado.Id);
                if (lembreteDb == null)
                {

                    return NotFound();

                }

                lembreteDb.Titulo = lembreteAtualizado.Titulo;
                lembreteDb.Descricao = lembreteAtualizado.Descricao;
                // lembreteDb.Data = lembreteAtualizado.Data;
                lembreteDb.Prioridade = lembreteAtualizado.Prioridade;
                // lembreteDb.Concluido = lembreteAtualizado.Concluido;
                
              

                context.SaveChanges();

                return Ok(new { message = "Lembrete atualizado com sucesso!" });
            }


    }
}

Controllers/LugaresController.cs
using Microsoft.AspNetCore.Mvc;
using RecentMemory.Contexts;

namespace RecentMemory.Controllers
{
    [Route("[Controller]")]
    public class LugaresController : Controller
    {
        RecentMemoryContext context = new RecentMemoryContext();

        public IActionResult Index()
        {
            var listaLugares = context.Lugares.ToList();

            ViewBag.lisatLugares = listaLugares;

            return View();
        }

    }
}

Views/Shared/_Layout.cshtml
@{
    var username = Context.Session.GetString("NomeUsuario");
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RecentMemory</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/select2/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RecentMemory.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RecentMemory</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Lembretes" asp-action="Index">Lembretes</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Contatos" asp-action="Index">Contatos</a>
                            </li>
                            
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Lugares" asp-action="Index">Lugares</a>
                            </li>

                        </ul>
                    </div>

                    <!-- Seção de perfil  -->
                <div class="d-flex align-items-center gap-3" style="border-left: 1px solid #e5e7eb; padding-left: 1.5rem;">
                <button onclick="window.location='@Url.Action("Index", "Configuracoes")'" 
        style="
            width: 40px; 
            height: 40px; 
            background: #0ea5e9; 
            border-radius: 50%; 
            display: flex; 
            align-items: center; 
            justify-content: center; 
            padding: 0;
            border: none;
            cursor: pointer;
        ">
    <img src="/imagem/39779.png" 
         alt="Configurações"
         style="
             width: 40px; 
             height: 40px; 
             border-radius: 50%;
         ">
</button>


                    <p>@username</p>

                    @if(string.IsNullOrEmpty(username))
                    {
                        <div "card-body"> 
                                <div class="d-none d-md-block">
                                    <!-- Login Button -->
                                    <a href="Login" class="btn btn-primary" style="background: #0ea5e9; border: none; padding: 8px 18px; border-radius: 6px; color: white; font-weight: 500; text-decoration: none; transition: background 0.2s;">
                                        Entrar
                                    </a>

                                </div>
                        </div>
                    }
                </div>
         </nav>
</header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - RecentMemory - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/select2/dist/js/select2.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    
</body>
</html>

Views/Shared/_LayoutCadastrar.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RecentMemory</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RecentMemory.styles.css" asp-append-version="true" />
</head>
<body>
    @RenderBody()
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RecentMemory</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RecentMemory.styles.css" asp-append-version="true" />
</head>
<body>
    @RenderBody()
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>